### ISSUE TITLE
Upgrade to Gulp 4

### ISSUE THREAD

**Issue by esausilva** [esausilva/jekyll-gulp-boilerplate#1]
The project is running on Gulp 3.9.1, but I would like it to be migrated to Gulp 4. There was some breaking changes in Gulp 4, specially around the syntax.

I will only accept changes to `gulpfile.js` (and obviously `package.json`/`package-lock.json`) in this PR.

- Create a feature branch to make the changes
- Make sure you run [Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEIA0IIAcYEtoDOyoAhgE5kQDuACuQkSiQG4S4Am6IARmSWAGs4MAMpZ+uKAHNkMMgFc4GSQThkYNPlIC2JZADMSAG1UYAVgQAeAIT6DhIktrgAZSXAPHTIcWVVlkHhJuAE8jaC4sMkkYAHUOGAALZAAOAAYMKIhVWL4sQKi4f2YPDDI4AEd5XHLNEh09JEMTJRBVbVxZBVaCSSkjOABFeQh4LsUMGGD49iTkACZJvlwjPoBhCG1dQKhoUpB5VQAVYMZm1QBfC6A) with the _single quote_ option enabled on `gulpfile.js` before submitting a PR
- Check that everything is working fine before submitting a PR

Have fun!

**Comment by mread1208** [comment]
I can take a look at this one

**Comment by esausilva** [comment]
@mread1208 Great! Thanks

**Comment by mread1208** [comment]
Sorry, I haven't been able to complete this task.  I've been running into lots of roadblocks both with npm and ruby permission issues (most likely my fault).  I was able to finally get around the node install issues:

1. Set python path [found here](https://github.com/aletheia-foundation/aletheia-app/issues/58#issuecomment-341957973)
    * Find python path for mac - `which python`
    *  `npm config set python /path/to/python`
1. EPERM Issues with npm: https://docs.npmjs.com/getting-started/fixing-npm-permissions
    * I ended up manually resetting my npm location and things started working.

However, I hit roadblock after roadblock getting Ruby working.  Mac's have ruby installed by default so you have to run something like [rbenv](https://github.com/rbenv/rbenv) on your machine in order to actually work with Ruby outside of Xcode.  I started going down that path, but then I was still getting issues with my gem installs.

I might hack away at this a little longer, but if someone else has the proper environments setup and working already feel free to take this one.

**Comment by esausilva** [comment]
@mread1208 Thanks for the update. And no worries, I'm not in a hurry to migrate this to Gulp 4, but I'd like to get it done at some point 👍

**Comment by mread1208** [comment]
Just opened the PR 😄.

I was able to fix all of my ruby issues by installed `rbenv` with homebrew, and running `brew doctor` to help me fix all of the permission issues I was having.  Once everything was installed, I was able to upgrade Gulp and start digging into the issues.

Hope this helps!
